name: Android CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'zulu'
          - name: Build and run unit tests with Gradle
            run: ./scripts/ci_unit.sh
          - name: Publish to Sonatype
            env:
              NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
              NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
            if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'bumptech/glide' }}
            run: ./gradlew publish -PNEXUS_USERNAME="${NEXUS_USERNAME}" -PNEXUS_PASSWORD="${NEXUS_PASSWORD}"

